export const VALIDATION = {
    EMAIL: "Email is required",
    VALID_EMAIL: "Email must be a valid email",
    FULL_NAME: "Full name is required",
    MOBILE_NUMBER: "Mobile number is required",
    PASSWORD: "Password is required",
    CONFIRM_PASSWORD: "Confirm password is required",
    PASSWORD_DOES_NOT_MATCH: "Passwords does not match",
    BIO: "Bio is required",
    DOB: "Please select your bithdate",
    BIO_CHARACTERS: "The Description should not be shorter than 100 characters",
    BIO_NOT_ONLY_NUMBERS: "The Description should not be only numbers.",
    DOCTORSPECIALITY: "Please select atleast one Speciality ",
    DOCTORSYMPTOM: "Please select atleast one Symptom",
    DOCTOREDUCATION: "Please select atleast one Education field",
    SELECT_PHOTOID: "Please select atleast one PhotoID",
    SELECT_REGISTER_DOCUMENT: "Please select atleast one Registration Document",
    TOTAL_EXPERIENCE: "Total Experience should required and must be greater than 0",
    GENDER: "Please select Your Gender",
    CLINIC_NAME: "Clinic name is required",
    BLOOD_GROUP:"Blood group is required",
    MARITAL_STATUS:"Marital status is required",
    HEIGHT:"Height is required",
    WEIGHT:"Weight is required",
    ADDRESS:"Address is required",
    PROFILE_PIC:"Profile is required",
    ALLERGIES:"Please select atleast one allergies",
    CURRENT_SYMPTOMS:"Please select atleast one current symptopms",
    PAST_SYMPTOMS:"Please select atleast one past symptoms",
    CHRONIC_ILLNESS:"Please select atleast one chronic illness",
    INJURIES:"Please select atleast one injuries",
    SURGERIES:"Please select atleast one surgeries",
    BANK_NAME: "Bank name is required",
    ACCOUNT_HOLDER_NAME: "Please enter account handler name",
    ACCOUNT_NUMBER: "Account number is required",
    CONFIRM_ACCOUNT_NUMBER: "Please enter confirm account number",
    IFSC_CODE: "IFSC code is required",
    ACCOUNT_NUMBER_NOT_MATCH: "Your account number does not match",
    ALPHA_NUMERIC_ONLY: "Special charactors are not allowed",
    CONSULTAION_FEES:"Please enter the fees for consultation",
    CONSULTAION_MODE:"Please select atleast one mode",
    FACILITIES : "Please select atleast one Facility",
    CLINIC_IMAGES : "Select atleast One image of your clinic"

}

